### ISSUE TITLE
Infrastructure for Web Development

### ISSUE THREAD

**Issue by nap** [corrinachow/interview-prep#1]
I felt like the README was missing some core concept for making work available to the public in the enterprise world.

Here's some ideas:

- Web Servers: NGINX or Apache
- Load Balancers: HAProxy
- Domain name and DNS in general
- Generating SSL/TLS certificate: https://letsencrypt.org
- Containerization: Docker
- Database and SQL: MySQL or PostgreSQL 
- The concept of Content Delivery Network (CDN)
- Shell Scripting: Bash

**Comment by corrinachow** [comment]
Thanks for the feedback @nap !

Some of those are covered in the [System Design Primer](https://github.com/donnemartin/system-design-primer)

**Web Servers: NGINX or Apache**
Briefly covered here: https://github.com/donnemartin/system-design-primer#reverse-proxy-web-server

**Load Balancers: HAProxy** 
Covered here https://github.com/donnemartin/system-design-primer#load-balancer

**Domain name and DNS in general**
Covered here: https://github.com/donnemartin/system-design-primer#domain-name-system

**Generating SSL/TLS certificate: https://letsencrypt.org**
Will add!

**Containerization: Docker**
Will also add!

**Database and SQL: MySQL or PostgreSQL**
https://github.com/donnemartin/system-design-primer#database (this also gets a bit more granular and compares key-value store, document store, wide column store)

**The concept of Content Delivery Network (CDN)**
Covered here: https://github.com/donnemartin/system-design-primer#content-delivery-network + caching

**Shell Scripting: Bash**
Will also add this, do you have a preferred resource?

Thanks again!

**Comment by nap** [comment]
I like this guide from Google: https://google.github.io/styleguide/shellguide.html

There's plenty of resources online that will expand on all the features talked about in the guide.
